sources: 
  - name: grant-ships
    handler: 
      graphql: 
        endpoint: https://{context.apiEndpoint:api.studio.thegraph.com/query/41101/grant-ships-arb/version/latest}
  - name: gs-voting
    handler: 
      graphql: 
        endpoint: https://indexer.dev.hyperindex.xyz/6410aa4/v1/graphql
    transforms:
      - filterSchema:
          filters:
            - "!Grant"
            - "!Project"
            - "!GrantShip"
            - "!GameManager"
            - "!RawMetadata"
            - "!Update"
      - autoTypeMerging: true
      # - autoTypeMerging: true
documents: 
  - './src/**/*.graphql'